// vue/src/views/Signup.vue
<template>
  <div class="min-h-screen flex flex-col">
    <Header />

    <main
      class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-primary/5 via-background to-primary-glow/5"
    >
      <div class="w-full max-w-md">
        <Card class="p-8 shadow-xl">
          <div class="text-center mb-8">
            <h1 class="text-3xl font-bold text-foreground mb-2">
              Create Account
            </h1>
            <p class="text-muted-foreground">
              Get started with TicketFlow today
            </p>
          </div>

          <form @submit="handleSubmit(onSubmit)" class="space-y-5">
            <div class="space-y-2">
              <Label for="name">Full Name</Label>
              <Input
                id="name"
                placeholder="John Doe"
                v-model="name"
                v-bind="nameAttrs"
                autocomplete="name"
                :class="{ 'border-destructive': errors.name }"
              />
              <p v-if="errors.name" class="text-sm text-destructive">
                {{ errors.name }}
              </p>
            </div>

            <div class="space-y-2">
              <Label for="email">Email Address</Label>
              <Input
                id="email"
                type="email"
                placeholder="you@example.com"
                v-model="email"
                v-bind="emailAttrs"
                autocomplete="email"
                :class="{ 'border-destructive': errors.email }"
              />
              <p v-if="errors.email" class="text-sm text-destructive">
                {{ errors.email }}
              </p>
            </div>

            <div class="space-y-2">
              <Label for="password">Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="Create a password"
                v-model="password"
                v-bind="passwordAttrs"
                autocomplete="new-password"
                :class="{ 'border-destructive': errors.password }"
              />
              <p v-if="errors.password" class="text-sm text-destructive">
                {{ errors.password }}
              </p>
            </div>

            <div class="space-y-2">
              <Label for="confirmPassword">Confirm Password</Label>
              <Input
                id="confirmPassword"
                type="password"
                placeholder="Confirm your password"
                v-model="confirmPassword"
                v-bind="confirmPasswordAttrs"
                autocomplete="new-password"
                :class="{ 'border-destructive': errors.confirmPassword }"
              />
              <p v-if="errors.confirmPassword" class="text-sm text-destructive">
                {{ errors.confirmPassword }}
              </p>
            </div>

            <Button type="submit" class="w-full" :disabled="isLoading">
              {{ isLoading ? "Creating account..." : "Create Account" }}
            </Button>
          </form>

          <div class="mt-6 text-center">
            <p class="text-sm text-muted-foreground">
              Already have an account?
              <RouterLink
                to="/login"
                class="text-primary font-medium hover:underline"
              >
                Sign in
              </RouterLink>
            </p>
          </div>
        </Card>
      </div>
    </main>

    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { useRouter } from "vue-router";
import { useForm, useField } from "vee-validate";
import * as yup from "yup";
import { toast } from "vue-sonner";

import Header from "@/components/Header.vue";
import Footer from "@/components/Footer.vue";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { useAuthStore } from "@/stores/authStore";
import { signupSchema } from "@/validation/authSchemas";

type SignupFormData = yup.InferType<typeof signupSchema>;

const router = useRouter();
const auth = useAuthStore();
const isLoading = ref(false);

const { handleSubmit, errors } = useForm<SignupFormData>({
  validationSchema: signupSchema,
  initialValues: {
    name: "",
    email: "",
    password: "",
    confirmPassword: "",
  },
});

const { value: name, ...nameAttrs } = useField<string>("name");
const { value: email, ...emailAttrs } = useField<string>("email");
const { value: password, ...passwordAttrs } = useField<string>("password");
const { value: confirmPassword, ...confirmPasswordAttrs } =
  useField<string>("confirmPassword");

const onSubmit = async (data: SignupFormData) => {
  isLoading.value = true;
  try {
    const result = await auth.signup(data.email, data.password, data.name);

    if (result.success) {
      toast.success("Account created successfully! Welcome to TicketFlow.");
      router.push("/dashboard");
    } else {
      toast.error(result.error || "Signup failed. Please try again.");
    }
  } catch {
    toast.error("An unexpected error occurred. Please try again.");
  } finally {
    isLoading.value = false;
  }
};

watch(
  () => auth.isAuthenticated,
  (isAuth) => {
    if (isAuth) router.push("/dashboard");
  },
  { immediate: true }
);
</script>

// react/src/pages/Signup.tsx
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { useAuthStore } from "@/store/authStore";
import toast from "react-hot-toast";
import { useState, useEffect } from "react";
import { signupSchema } from "@/validation/authSchemas";

type SignupFormData = yup.InferType<typeof signupSchema>;

const Signup = () => {
  const navigate = useNavigate();
  const { signup, isAuthenticated } = useAuthStore();
  const [isLoading, setIsLoading] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<SignupFormData>({
    resolver: yupResolver(signupSchema),
  });

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/dashboard");
    }
  }, [isAuthenticated, navigate]);

  const onSubmit = async (data: SignupFormData) => {
    setIsLoading(true);
    try {
      const result = await signup(data.email, data.password, data.name);

      if (result.success) {
        toast.success("Account created successfully! Welcome to TicketFlow.");
        navigate("/dashboard");
      } else {
        toast.error(result.error || "Signup failed. Please try again.");
      }
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (error) {
      toast.error("An unexpected error occurred. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-primary/5 via-background to-primary-glow/5">
        <div className="w-full max-w-md">
          <Card className="p-8 shadow-xl">
            <div className="text-center mb-8">
              <h1 className="text-3xl font-bold text-foreground mb-2">
                Create Account
              </h1>
              <p className="text-muted-foreground">
                Get started with TicketFlow today
              </p>
            </div>

            <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
              <div className="space-y-2">
                <Label htmlFor="name">Full Name</Label>
                <Input
                  id="name"
                  placeholder="John Doe"
                  autoComplete="name"
                  {...register("name")}
                  className={errors.name ? "border-destructive" : ""}
                />
                {errors.name && (
                  <p className="text-sm text-destructive">
                    {String(errors.name?.message || "")}
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="email">Email Address</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="you@example.com"
                  autoComplete="email"
                  {...register("email")}
                  className={errors.email ? "border-destructive" : ""}
                />
                {errors.email && (
                  <p className="text-sm text-destructive">
                    {String(errors.email?.message || "")}
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="Create a password"
                  autoComplete="new-password"
                  {...register("password")}
                  className={errors.password ? "border-destructive" : ""}
                />
                {errors.password && (
                  <p className="text-sm text-destructive">
                    {String(errors.password?.message || "")}
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="confirmPassword">Confirm Password</Label>
                <Input
                  id="confirmPassword"
                  type="password"
                  placeholder="Confirm your password"
                  autoComplete="new-password"
                  {...register("confirmPassword")}
                  className={errors.confirmPassword ? "border-destructive" : ""}
                />
                {errors.confirmPassword && (
                  <p className="text-sm text-destructive">
                    {String(errors.confirmPassword?.message || "")}
                  </p>
                )}
              </div>

              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? "Creating account..." : "Create Account"}
              </Button>
            </form>

            <div className="mt-6 text-center">
              <p className="text-sm text-muted-foreground">
                Already have an account?{" "}
                <Link
                  to="/login"
                  className="text-primary font-medium hover:underline"
                >
                  Sign in
                </Link>
              </p>
            </div>
          </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Signup;
