// react/src/pages/Login.tsx
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as yup from "yup";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { useAuthStore } from "@/store/authStore";
import { toast } from "sonner";
import { useState, useEffect } from "react";
import { loginSchema } from "@/validation/authSchemas";

type LoginFormData = yup.InferType<typeof loginSchema>;

const Login = () => {
  const navigate = useNavigate();
  const { login, isAuthenticated } = useAuthStore();
  const [isLoading, setIsLoading] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginFormData>({
    resolver: yupResolver(loginSchema),
  });

  useEffect(() => {
    if (isAuthenticated) {
      navigate("/dashboard");
    }
  }, [isAuthenticated, navigate]);

  const onSubmit = async (data: LoginFormData) => {
    setIsLoading(true);
    try {
      const result = await login(data.email, data.password);

      if (result.success) {
        toast.success("Login successful! Welcome back.");
        navigate("/dashboard");
      } else {
        toast.error(result.error || "Login failed. Please try again.");
      }
    } catch (error) {
      toast.error("An unexpected error occurred. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      <main className="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-linear-to-br from-primary/5 via-background to-primary-glow/5">
        <div className="w-full max-w-md">
          <Card className="p-8 shadow-xl">
            <div className="text-center mb-8">
              <h1 className="text-3xl font-bold text-foreground mb-2">
                Welcome Back
              </h1>
              <p className="text-muted-foreground">
                Sign in to your account to continue
              </p>
            </div>

            <form onSubmit={handleSubmit(onSubmit)} className="space-y-5">
              <div className="space-y-2">
                <Label htmlFor="email">Email Address</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="you@example.com"
                  autoComplete="email"
                  {...register("email")}
                  className={errors.email ? "border-destructive" : ""}
                />
                {errors.email && (
                  <p className="text-sm text-destructive">
                    {String(errors.email?.message || "")}
                  </p>
                )}
              </div>

              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input
                  id="password"
                  type="password"
                  placeholder="Enter your password"
                  autoComplete="current-password"
                  {...register("password")}
                  className={errors.password ? "border-destructive" : ""}
                />
                {errors.password && (
                  <p className="text-sm text-destructive">
                    {String(errors.password?.message || "")}
                  </p>
                )}
              </div>

              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading ? "Signing in..." : "Sign In"}
              </Button>
            </form>

            <div className="mt-6 text-center">
              <p className="text-sm text-muted-foreground">
                Don't have an account?{" "}
                <Link
                  to="/signup"
                  className="text-primary font-medium hover:underline"
                >
                  Sign up
                </Link>
              </p>
            </div>
          </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Login;

// vue/src/views/Login.vue
<template>
  <div class="min-h-screen flex flex-col">
    <Header />

    <main
      class="flex-1 flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-primary/5 via-background to-primary-glow/5"
    >
      <div class="w-full max-w-md">
        <Card class="p-8 shadow-xl">
          <div class="text-center mb-8">
            <h1 class="text-3xl font-bold text-foreground mb-2">
              Welcome Back
            </h1>
            <p class="text-muted-foreground">
              Sign in to your account to continue
            </p>
          </div>

          <form @submit="handleSubmit(onSubmit)" class="space-y-5">
            <div class="space-y-2">
              <Label for="email">Email Address</Label>
              <Input
                id="email"
                type="email"
                placeholder="you@example.com"
                v-model="email"
                v-bind="emailAttrs"
                :class="{ 'border-destructive': errors.email }"
                autocomplete="email"
              />
              <p v-if="errors.email" class="text-sm text-destructive">
                {{ errors.email }}
              </p>
            </div>

            <div class="space-y-2">
              <Label for="password">Password</Label>
              <Input
                id="password"
                type="password"
                placeholder="Enter your password"
                v-model="password"
                v-bind="passwordAttrs"
                :class="{ 'border-destructive': errors.password }"
                autocomplete="current-password"
              />
              <p v-if="errors.password" class="text-sm text-destructive">
                {{ errors.password }}
              </p>
            </div>

            <Button type="submit" class="w-full" :disabled="isLoading">
              {{ isLoading ? "Signing in..." : "Sign In" }}
            </Button>
          </form>

          <div class="mt-6 text-center">
            <p class="text-sm text-muted-foreground">
              Don't have an account?
              <RouterLink
                to="/signup"
                class="text-primary font-medium hover:underline"
              >
                Sign up
              </RouterLink>
            </p>
          </div>
        </Card>
      </div>
    </main>

    <Footer />
  </div>
</template>

<script setup lang="ts">
import { ref, watchEffect } from "vue";
import { useRouter } from "vue-router";
import { useForm, useField } from "vee-validate";
import * as yup from "yup";
import { toast } from "vue-sonner";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card } from "@/components/ui/card";
import Header from "@/components/Header.vue";
import Footer from "@/components/Footer.vue";
import { useAuthStore } from "@/stores/authStore";
import { loginSchema } from "@/validation/authSchemas";

type LoginFormData = yup.InferType<typeof loginSchema>;

const router = useRouter();
const authStore = useAuthStore();
const { login, isAuthenticated } = authStore;

const isLoading = ref(false);

const { handleSubmit, errors } = useForm<LoginFormData>({
  validationSchema: loginSchema,
  initialValues: {
    email: "",
    password: "",
  },
});

const { value: email, ...emailAttrs } = useField<string>("email");
const { value: password, ...passwordAttrs } = useField<string>("password");

watchEffect(() => {
  if (isAuthenticated) {
    router.push("/dashboard");
  }
});

const onSubmit = async (data: LoginFormData) => {
  isLoading.value = true;
  try {
    const result = await login(data.email, data.password);
    if (result.success) {
      toast.success("Login successful! Welcome back.");
      router.push("/dashboard");
    } else {
      toast.error(result.error || "Login failed. Please try again.");
    }
  } catch (err) {
    toast.error("An unexpected error occurred. Please try again.");
  } finally {
    isLoading.value = false;
  }
};
</script>
